name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: . # Specify the build context (root directory)
          dockerfile: Dockerfile # Path to your Dockerfile if not in the root directory
          push: true
          tags: docker.io/***/demo-app:main-657c49d
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
